### ISSUE TITLE
Support for hg38

### ISSUE THREAD

**Issue by annahyan** [markowetzlab/scDNAseq-workflow#22]
Hi, any chance of supporting hg38 in the near future?

**Comment by leachim** [comment]
You can already use hg38 by changing the genome variable in the scAbsolute R script. However, I would strongly advise sticking to hg19,  since we have done quite a bit of optimization on the bin annotations, using public data that was only available for hg19. Also, for the copy number problem, I would not expect there to be massive differences between hg19/hg38.
Also let me know if you want to use the scUnique part of the pipeline, we will release the paper and the code very soon, so happy to give you early access if you want to give that part a try.

**Comment by leachim** [comment]
To be exact, you should be able to run the scAbsolute pipeline by just changing the genome variable in the config to hg38. I don't think I we currently support the density estimation for that part at the moment, so turn that off. Should be fairly simple to extend it to support hg38, though, if you really need it.

**Comment by annahyan** [comment]
I tried running with hg38 by changing the assembly in the config.yaml file and it didn't work (I didn't try the density estimation) but I guess I will stick to hg19 at the moment.

> Also let me know if you want to use the scUnique part of the pipeline, we will release the paper and the code very soon, so happy to give you early access if you want to give that part a try.

Certainly, I'd appreciate early access to scUnique. Thank you!

**Comment by leachim** [comment]
I have invited you to the repository; you should have read access to it now. Let me know if you have any issues with it, you might have to wait for the release of the preprint to understand how it works, but it isn't far off now.

**Comment by annahyan** [comment]
Thank you very much and looking forward to the preprint!

**Comment by leachim** [comment]
Also, I checked this, and you are right; there are a few bugs when running with GRCh38. In principle, it's easy to extend it to the GRCh38 build, but it would require adding additional files for the cell cycle annotation, optionally better blacklisting information (that data is currently only available for the GRCh37 build), and genome build info for read density estimation. Will add this to future milestones. We will not support this for now, as I don't think it makes a difference in copy number calling quality and might even be detrimental given that we can't use the public info to more carefully select bins.
