### ISSUE TITLE
scUnique segmentation sensitivity

### ISSUE THREAD

**Issue by annahyan** [markowetzlab/scDNAseq-workflow#25]
Hi, 

I managed to run scUnique but the segmentation seems too strict for our data. Is there a parameter I could play with akin to gamma in the copynumber package to fine-tune the granularity?

Thanks,
Anna

**Comment by leachim** [comment]
You can change the sensitivity of the initial scAbsolute segmentation (via the change_prob variable). It is a very conservative segmentation by default (change_prob=1e-3) and so you could try to increase it to 1e-2 or higher to pick up more copy number changes. This can be changed in the worflow/scripts/run_scAbsolute.R script
For scUnique, the variable to change is again change_prob; it is encoded as part of the script calling, but you can just remove the if else statement in line 133-135 of the run_scUnique.R script, and hard code it to a value of your liking. Again, values closer to 1 should be more sensitive, so I would suggest increasing it to 0.1 or 0.2
There is a graph in the scUnique publication that we will publish soon with a precision recall curve for this parameter.

**Comment by leachim** [comment]
Maybe as a side comment, if you change it in scAbsolute the runtime will increase quite a bit, because you will get many more segments and MEDICC2 is relatively slow. So I would first try to change the scUnique variable, unless you believe that the copy number trees are really wrong, then you can try to play around with the scAbsolute parameter.

**Comment by annahyan** [comment]
Thanks! I'll play around with the parameters!
